# Generated by Django 5.0 on 2023-12-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100, verbose_name='Field 1')),
                ('field2', models.IntegerField(verbose_name='Field 2')),
            ],
            options={
                'verbose_name': 'Another Model',
                'verbose_name_plural': 'Another Models',
            },
        ),
    ]
